//usage: 6ケタで最終仕様月を表す（西暦下2ケタ＋月2ケタ+その月のサークル使用回2ケタ）

const musicData = [

    {
        title: "La Pantera Mambo",
        artist: ["La-33", "(Covered by Zumba)"],
        genre: ["Salsa", "Mambo"],
        type: "MegaMix 14",
        category: ["Traditional", "Distinctive"],
		tempo: "1",
		usage: "241003",
		memo: "「豹のマンボ」サルサのステップに合わせてみんなで威嚇「シャーッ！」",
        link: "https://youtu.be/KLsGFDeiY5I?si=UpW4Qp9ZdjX6hSo7"
    },
    {
        title: "Bonito",
        artist: ["Zumba"],
        genre: ["Samba", "Batucada"],
        type: "MegaMix 14",
        category: ["Relaxing", "Distinctive"],
		tempo: "1",
		usage: "241003",
		memo: "雰囲気はまるでセルジオ・メンデスのサンバ・ボサノヴァ。Bonito：「美しい」誰かを前に心が揺れちゃう、そんな振付です。",
        link: ""
    },
    {
        title: "Me Descontrola",
        artist: ["Ronald Borjas", "feat.", "Motif"],
        genre: ["Salsa"],
        type: "FitnessVariation 26",
        category: ["Rhythmic"],
		tempo: "1",
		usage: "240602",
		memo: "",
        link: "https://youtu.be/M7oZquZM8to?si=2jdbQVxlOVjLPQGQ",
    },
    {
        title: "Amor De Lejos",
        artist: ["Tati K"],
        genre: ["Cumbia"],
        type: "FitnessVariation 26",
        category: ["Dark", "Traditional"],
		tempo: "1",
		usage: "240601",
		memo: "都会の夜のイメージ。音に合わせた力強い動きとクンビアのビートに合わせた滑らかな動きが特徴です。",
        link: "https://youtu.be/Rgq2-DYsQfM?si=EMH1UPicZE0Tw-50"
    },
    {
        title: "Cumbhangra",
        artist: ["Zumba"],
        genre: ["Bhangra", "Cumbia"],
        type: "FitnessVariation 31",
        category: ["Traditional"],
		tempo: "1",
		usage: "240402",
		memo: "Cumbia + BhangraでCumbhangra ですがベリーダンスのステップも入れています。",
        link: ""
    },
    {
        title: "Gimme Five",
        artist: ["Zumba"],
        genre: ["Bachata", "Batucada"],
        type: "ZIN 44",
        category: ["Powerful"],
		tempo: "1",
		usage: "240103",
		memo: "",
        link: ""
    },
    {
        title: "Tijuana Nights",
        artist: ["Zumba"],
        genre: ["Quebradita"],
        type: "ZIN 47",
        category: ["Traditional", "Powerful", "Distinctive"],
		tempo: "1",
		usage: "240701",
		memo: "「ティファナでの夜」Tijuanaはメキシコの都市名らしいです。イントロの「ヤ―！」を聞いて振付がすぐに決まりました笑",
        link: ""
    },
    {
        title: "Ice Cream And Cake",
        artist: ["Oro Solido"],
        genre: ["Merengue"],
        type: "MegaMix 48",
        category: ["Rhythmic"],
		tempo: "1",
		usage: "240803",
		memo: "",
        link: "https://youtu.be/kkY0PeMaZKA?si=JqhUCGc6MCEwfLZY"
    },
    {
        title: "Ministry of Road (M.O.R)",
        artist: ["Machel Montano"],
        genre: ["Reggae", "Soca"],
        type: "MegaMix 48",
        category: ["Powerful", "Blast"],
		tempo: "1",
		usage: "231204",
		memo: "",
        link: "https://youtu.be/zUxfgSdYNN4"
    },
    {
        title: "Better When I'm Dancing",
        artist: ["Meghan Trainor", "(Covered by Zumba)"],
        genre: ["Pop", "Calypso"],
        type: "MegaMix51",
        category: ["Bright", "Relaxing"],
		tempo: "1",
		usage: "240901",
		memo: "明るい気持ちになれる曲。「一緒に踊ろう？その方が楽しいでしょ？」という歌詞やテーマが大好き。スヌーピーの映画のテーマ曲らしいです。",
        link: "https://youtu.be/pkCyfBibIbI?si=TCtP617f0NFinUk-"
    },
    {
        title: "Bailando",
        artist: ["Enrique Igresias", "feat.", "Descemer Bueno", "Gente De Zona"],
        genre: ["Reggaeton", "Flamenco"],
        type: "ZIN 52",
        category: ["Emotional", "Relaxing"],
		tempo: "1",
		usage: "240904",
		memo: "",
        link: "https://youtu.be/NUsoVlDFqZg?si=R1KZNTg4obtd4uei"
	},
    {
        title: "Milonga Con Azucar",
        artist: ["Zumba"],
        genre: ["Milonga", "Tango"],
        type: "MegaMix 52",
        category: ["Cool", "Emotional"],
		tempo: "1",
		usage: "231202",
		memo: "",
        link: ""
    },
    {
        title: "Sal A Bailar",
        artist: ["La Poderosa", "Víctor Manuelle", "(Covered by Zumba)"],
        genre: ["Salsa", "Batucada"],
        type: "MegaMix 52",
        category: ["Bright", "Blast", "Rhythmic"],
		tempo: "1",
		usage: "2401001",
		memo: "Zumba版はVíctor Manuelleのアレンジを基にしていますね。",
        link: "https://youtu.be/zAlJdUmMzsA?si=7zIIdMYB1fqdvgO3"
    },
    {
        title: "Dejenme Vivir",
        artist: ["Amarfis", "La Banda De Atakke"],
        genre: ["Merengue"],
        type: "MegaMix 52",
        category: ["Powerful", "Rhythmic"],
		tempo: "1",
		usage: "240703",
		memo: "速い！激しい！メレンゲの楽曲。尊敬するインストラクターの振付をを一部真似してます（許可頂きました！）ソカ・ダンスホールで有名なMachel Montanoの曲に似たのがあるのが少し気になってます笑。",
        link: "https://youtu.be/0NSJaxY_vzM?si=nGYg2G-1juxyrww-"
    },
    {
        title: "Mas Que Tu Amigo",
        artist: ["Zumba"],
        genre: ["Salsa",],
        type: "ZIN 55",
        category: ["Emotional", "Rhythmic"],
		tempo: "1",
		usage: "240501",
		memo: "ZIN 106にある同名の曲はこの曲のアレンジみたいですね。哀愁を感じられる旋律が大好きです。振付はクンビアVer.から拝借。",
        link: ""
    },
    {
        title: "Que Es Lo Que Dice",
        artist: ["Robert Taylor"],
        genre: ["Salsa Choke"],
        type: "MegaMix 55",
        category: ["Experimental"],
		tempo: "1",
		usage: "230204",
		memo: "",
        link: "https://youtu.be/4nXOvde7030"
    },
    {
        title: "Tu Mi Medicina",
        artist: ["Andy Quintero"],
        genre: ["Merengue", "Pop"],
        type: "MegaMix 58",
        category: ["Bright"],
		tempo: "1",
		usage: "231001",
		memo: "シンプルな振付で踊れるメレンゲ曲。",
        link: "https://youtu.be/4Xr24SmSvBI?si=tjysHq5_iqdROZ__"
	},
    {
        title: "Rompa la Pompa",
        artist: ["Zumba Studio"],
        genre: ["Cumbia", "Oriental","Fusion"],
        type: "ZIN 58",
        category: ["Powerful", "Experimental"],
		tempo: "1",
		usage: "240403",
		memo: "",
        link: ""
	},
    {
        title: "Despacito",
        artist: ["Luis Fonsi", "feat.", "Victor Manuelle"],
        genre: ["Salsa"],
        type: "MegaMix 58",
        category: ["Emotional", "Relaxing"],
		tempo: "1",
		usage: "240603",
		memo: "",
        link: ""
	},
    {
        title: "Sola",
        artist: ["Zumba"],
        genre: ["Reggaeton", "Bhangra"],
        type: "ZIN 59",
        category: ["Powerful", "Experimental"],
		tempo: "1",
		usage: "240701",
		memo: "",
        link: ""
	},
	{
        title: "Zumba Fuego",
        artist: ["Zumba"],
        genre: ["Cumbia", "Flamenco"],
        type: "ZIN 59",
        category: ["Traditional"],
		tempo: "1",
		usage: "240104",
		memo: "",
        link: ""
	},
    {
        title: "Cumbia Anthem",
        artist: ["El Dusty", "feat.", "Happy Colors", "(Covered by Zumba)"],
        genre: ["Cumbia", "Urban"],
        type: "ZIN 60",
        category: ["Traditional", "Experimental"],
		tempo: "1",
		usage: "230901",
		memo: "",
        link: "https://youtu.be/MT02fwtyVVU"
	},
    {
        title: "Indian Passion",
        artist: ["Zumba"],
        genre: ["Bhangra", "Fusion"],
        type: "ZIN 61",
        category: ["Traditional", "Rhythmic"],
		tempo: "1",
		usage: "240103",
		memo: "",
        link: ""
	},
    {
        title: "Cara de Nino",
        artist: ["Jerry Rivera", "(Covered by Zumba)"],
        genre: ["Salsa"],
        type: "ZIN 63",
        category: ["Emotional", "Rhythmic"],
		tempo: "1",
		usage: "240501",
		memo: "長めのサルサ曲。",
        link: "https://youtu.be/HagwTbmyyVA?si=uHYyZ6i0pBpbHGwJ"
	},
    {
        title: "No Voy A Llorar",
        artist: ["Carolina La O", "(feat.)", "Robert Taylor"],
        genre: ["Merengue", "pop"],
        type: "ZIN 64",
        category: ["Rhythmic"],
		tempo: "1",
		usage: "231204",
		memo: "",
        link: "https://youtu.be/-41v6jLOcas?si=8R_pafH9PXLtyuzn"
	},
    {
        title: "Macarena (Zumba Remix)",
        artist: ["Los Del Rio"],
        genre: ["Salsa"],
        type: "ZIN 64",
        category: ["Distinctive", "Rhythmic"],
		tempo: "1",
		usage: "231003",
		memo: "",
        link: "https://youtu.be/cV0FxPZ3YR0?si=aHcmsR-GDEMVLyrO"
	},
    {
        title: "Como En Las Vegas",
        artist: ["Olga Tañon"],
        genre: ["Reggaeton"],
        type: "MegaMix 65",
        category: ["Cool", "Distinctive"],
		tempo: "1",
		usage: "240804",
		memo: "手の難しい振付はダンスホールから取り入れました。",
        link: "https://youtu.be/HJ6mZZbN2AE?si=snPj72lOa9JGhufv"
	},
    {
        title: "Yo Voy Contigo Colombia",
        artist: ["Moises Angulo"],
        genre: ["Cumbia"],
        type: "MegaMix 65",
        category: ["Bright", "Traditional"],
		tempo: "1",
		usage: "240604",
		memo: "",
        link: "https://youtu.be/yBDBSx1dHX0?si=cLOY4NvxgZIKluE7"
	},
    {
        title: "A Mi Me Gusta",
        artist: ["Robert Taylor"],
        genre: ["Merengue", "Batucada"],
        type: "MegaMix 66",
        category: ["Blast", "Rhythmic", "Distinctive"],
		tempo: "1",
		usage: "240704",
		memo: "♡を投げまくる振付の曲。",
        link: ""
	},
    {
        title: "Rub A Bum",
        artist: ["Play-N-Skillz", "feat.", "Jenn Morel", "Joelli"],
        genre: ["Reggaeton", "Dembow"],
        type: "MegaMix 67",
        category: ["Powerful", "Rhythmic"],
		tempo: "1",
		usage: "240602",
		memo: "",
        link: "https://youtu.be/HBntvaWP9qc?si=8QN8Z0LU7LJUyirP"
	},
    {
        title: "Plastico",
        artist: ["Willie Colon", "(Covered by Zumba)"],
        genre: ["Salsa",],
        type: "ZIN 55",
        category: ["Emotional", "Rhythmic"],
		tempo: "1",
		usage: "240803",
		memo: "とっても長いサルサ曲。「」",
        link: ""
    },
    {
        title: "Bailalo",
        artist: ["Armando", "&", "Heidy"],
        genre: ["Dembow"],
        type: "ZIN 68",
        category: ["Powerful", "Experimental", "Distinctive"],
		tempo: "1",
		usage: "240504",
		memo: "おなかに効かせたい一曲。hala!→腹！の空耳。",
        link: "https://youtu.be/wwrgDrXK4i8?si=oTEi4E9C6aGcmeW7"
	},
    {
        title: "Roxanne",
        artist: ["Zumba"],
        genre: ["Bachata"],
        type: "ZIN 70",
        category: ["Cool"],
		tempo: "1",
		usage: "240603",
		memo: "",
        link: ""
	},
    {
        title: "That’s What I Like (Zumba Remix)",
        artist: ["Bruno Mars"],
        genre: ["Trap", "Reggaeton"],
        type: "ZIN 70",
        category: ["Cool", "Experimental"],
		tempo: "1",
		usage: "2301104",
		memo: "ブルーノマーズの有名な楽曲をZumbaがアレンジ！トラップの要素が強い後半、",
        link: "https://youtu.be/PMivT7MJ41M?si=QW6itaZPAENZ3vRC"
	},
    {
        title: "Solo Tu",
        artist: ["Jaider White", "feat.", "Robert Taylor"],
        genre: ["Merengue", "Pop"],
        type: "ZIN 70",
        category: ["Rhythmic"],
		tempo: "1",
		usage: "241001",
		memo: "ZIN 112のあ",
        link: ""
	},
    {
        title: "Tumbao",
        artist: ["Prince Royce", "feat.", "Gente de Zona", "Arturo Sandoval", "(Covered by Zumba)"],
        genre: ["Bachata"],
        type: "ZIN 71",
        category: ["Emotional"],
		tempo: "1",
		usage: "240802",
		memo: "クールダウンとして用いているインストラクターが多いイメージです。",
        link: "https://youtu.be/B6wTkZwq7nI"
	},
    {
        title: "Esta Noche",
        artist: ["Jeison el Brother"],
        genre: ["Salsa"],
        type: "MegaMix 72",
        category: ["Bright", "Rhythmic"],
		tempo: "1",
		usage: "231201",
		memo: "",
        link: "https://youtu.be/ENZuMMdKtC8?si=JLfoRnsBW6uTq9nd"
	},
    {
        title: "Baila Mi Cumbia",
        artist: ["Jeison el Brother"],
        genre: ["Cumbia", "Reggaeton"],
        type: "MegaMix73",
        category: ["Powerful", "Experimental"],
		tempo: "1",
		usage: "231002",
		memo: "",
        link: "https://youtu.be/NtNNiudOEgM?si=ISTOVxsELjEA1an8"
	},
    {
        title: "El Clavo",
        artist: ["Prince Royce"],
        genre: ["Reggaeton"],
        type: "ZIN 74",
        category: ["Emotional", "Cool"],
		tempo: "1",
		usage: "240302",
		memo: "バチャータで有名なプリンス・ロイスのレゲトン楽曲。",
        link: "https://youtu.be/FCfP7v9x8HI?si=8HtNwsyAF-ghp1-X"
	},
    {
        title: "ODWAN [One Day With A Mexican]",
        artist: ["Broz Rodriguez", "feat.", "Lujavo", "Toy Selectah"],
        genre: ["EDM", "Cumbia"],
        type: "ZIN 74",
        category: ["Powerful", "Dark", "Blast"],
		tempo: "1",
		usage: "240304",
		memo: "クンビアってなんだっけ？となる、ダンスミュージック要素満載の楽曲。",
        link: "https://youtu.be/1AtvhzMDnFg"
	},
    {
        title: "No Me Deles Asi",
        artist: ["Max Pizzolante"],
        genre: ["Merengue"],
        type: "ZIN 75",
        category: ["Rhythmic"],
		tempo: "1",
		usage: "240203",
		memo: "",
        link: "https://youtu.be/FTzS5Oa03WE"
	},
    {
        title: "Doh Play Dat",
        artist: ["Machel Montano"],
        genre: ["Soca"],
        type: "ZIN 75",
        category: ["Powerful", "Rhythmic"],
		tempo: "1",
		usage: "240301",
		memo: "",
        link: "https://youtu.be/UI2XXgbnyrU?si=uUI-iToCd9CNkrE1"
	},
    {
        title: "Familiar",
        artist: ["Liam Payne", "feat.", "J.Balvin"],
        genre: ["Latin"],
        type: "ZIN 75",
        category: ["Cool", "Emotional"],
		tempo: "1",
		usage: "240701",
		memo: "",
        link: "https://youtu.be/oWw1BcFhk-k?si=lGO9BNbHEU6OZDTS"
	},
    {
        title: "Telephone Soghayar",
        artist: ["Hakim"],
        genre: ["Bellydance"],
        type: "ZIN 75",
        category: ["Distinctive", "Traditional"],
		tempo: "1",
		usage: "240901",
		memo: "",
        link: "https://youtu.be/Qa56XzB7yIk?si=s2bo-Kikw7cTcjIC"
	},
    {
        title: "Lista Pa' Vivir",
        artist: ["Carolina Sabino"],
        genre: ["Cumbia"],
        type: "ZIN 77",
        category: ["Bright", "Rhythmic"],
		tempo: "1",
		usage: "240501",
		memo: "",
        link: ""
	},
    {
        title: "Metal Bhangg",
        artist: ["Zumba"],
        genre: ["Bhangra", "EDM"],
        type: "MegaMix 78",
        category: ["Powerful", "Traditional", "Blast"],
		tempo: "1",
		usage: "240903",
		memo: "",
        link: ""
	},
    {
        title: "Bailar Pegaito",
        artist: ["DEMOglias"],
        genre: ["Merengue"],
        type: "MegaMix 79",
        category: ["Powerful", "Blast"],
		tempo: "1",
		usage: "240104",
		memo: "",
        link: "https://youtu.be/lYzPoNQvCoE"
	},
    {
        title: "Munequita Linda",
        artist: ["Juan Magan", "Deorro", "MAKJ"],
        genre: ["Merengue", "EDM"],
        type: "ZIN 79",
        category: ["Powerful", "Cool"],
		tempo: "1",
		usage: "240103",
		memo: "",
        link: "https://youtu.be/v6lELbZiZG8?si=FASZyEH_jaR_UnON"
	},
    {
        title: "Batu-Cuica",
        artist: ["Zumba"],
        genre: ["Batucada"],
        type: "ZIN 80",
        category: ["Traditional", "Rhythmic"],
		tempo: "1",
		usage: "231103",
		memo: "",
        link: ""
	},
    {
        title: "Mas Que Bien (Zumba Remix)",
        artist: ["Juan Por Dios"],
        genre: ["Quebradita", "Hip-hop"],
        type: "ZIN 80",
        category: ["Rhythmic", "Powerful"],
		tempo: "1",
		usage: "231004",
		memo: "",
        link: "https://youtu.be/4vjLdni4OVQ"
	},
    {
        title: "Pegadito (Zumba Remix)",
        artist: ["Play-N-Skillz"],
        genre: ["Reggaeton", "Cha-cha-cha"],
        type: "ZIN 80",
        category: ["Dark", "Cool"],
		tempo: "1",
		usage: "230904",
		memo: "",
        link: "https://youtu.be/O8_LW71sfE0"
	},
    {
        title: "Sueltara",
        artist: ["Jorge Luis Chasin"],
        genre: ["Cumbia", "Batucada"],
        type: "ZIN 80",
        category: ["Powerful", "Traditional", "Distinctive"],
		tempo: "1",
		usage: "240802",
		memo: "",
        link: "https://youtu.be/BhnLw2mOaBU"
	},
    {
        title: "Tik Tak Tik Tok",
        artist: ["Chune", "Cami V"],
        genre: ["Bachata", "Dembow"],
        type: "MegaMix 80",
        category: ["Bright", "Rhythmic"],
		tempo: "1",
		usage: "231203",
		memo: "",
        link: "https://youtu.be/a2OKyeX_R1g"
	},
    {
        title: "Tu Flow",
        artist: ["Alex Tatoo", "feat.", "Cooper J."],
        genre: ["Dembow", "Moombathon"],
        type: "MegaMix 80",
        category: ["Powerful", "Distinctive"],
		tempo: "1",
		usage: "240504",
		memo: "",
        link: "https://youtu.be/LZjS9euH04c?si=IzZIAMorhfaJfOt_"
	},
    {
        title: "Parecen Viernes",
        artist: ["Mark Anthony"],
        genre: ["Salsa"],
        type: "ZIN 81",
        category: ["Emotional"],
		tempo: "1",
		usage: "241003",
		memo: "",
        link: "https://youtu.be/AsCnKFzhFSA?si=TA5GzfEHe3NjYOTR"
	},
    {
        title: "Se Te Ve",
        artist: ["Ray El Ingeniero"],
        genre: ["Cumbia", "Bhangra", "Bellydance"],
        type: "ZIN 81",
        category: ["Traditional", "Relaxing"],
		tempo: "1",
		usage: "240403",
		memo: "",
        link: ""
	},
    {
        title: "3G",
        artist: ["Wisin", "feat.", "Jon Z", "Chezina"],
        genre: ["Reggaeton", "Urban"],
        type: "ZIN 82",
        category: ["Dark", "Powerful"],
		tempo: "1",
		usage: "231102",
		memo: "",
        link: "https://youtu.be/y5Hf0O1nWMQ?si=IKRUF7IJ-6BP8-Zp"
	},
    {
        title: "Black Zombie",
        artist: ["The Zombie Kids"],
        genre: ["Merengue", "Trap"],
        type: "ZIN 82",
        category: ["Rhythmic", "Dark", "Experimental"],
		tempo: "1",
		usage: "231004",
		memo: "",
        link: "https://youtu.be/tXA7zOQhwPA?si=4BpTEIFYSAakRDjh"
	},
    {
        title: "Piedra, Papel o Tijera",
        artist: ["Bela Hamilton"],
        genre: ["Reggaeton", "Urban"],
        type: "ZIn 82",
        category: ["Cool", "Dark"],
		tempo: "1",
		usage: "231203",
		memo: "",
        link: "https://youtu.be/D3nmBUEBJYs"
	},
    {
        title: "Bailando",
        artist: ["Zumba"],
        genre: ["Merengue"],
        type: "ZIN 83",
        category: ["Cool", "Rhythmic", "Bright"],
		tempo: "1",
		usage: "240602",
		memo: "",
        link: ""
	},
    {
        title: "Wepa",
        artist: ["Max Pizzolante", "feat.", "Victor Drija"],
        genre: ["Bachata", "Dembow"],
        type: "ZIN 83",
        category: ["Cool", "Dark"],
		tempo: "1",
		usage: "240804",
		memo: "フィーチャーされている方は最近のZumba Volumeにも楽曲が収録されているアーティストですね。デンボウパートが激しめ。",
        link: "https://youtu.be/CBqCOwv4c6E?si=xqUMy4b9GVuCrPy9"
	},
    {
        title: "Escucha Mujer (Zumba Remix)",
        artist: ["Zona Prieta", "feat.", "Aldo Ranks"],
        genre: ["Pacific", "Urban"],
        type: "MegaMix 85",
        category: ["Powerful", "Distinctive"],
		tempo: "1",
		usage: "241004",
		memo: "ジャンプの時は腹筋に力を入れること、あとは表情。それ以外は何も気にせず踊る曲！",
        link: "https://youtu.be/TD1UaFbGQNo?si=nXNej9p1JU5zI_aV"
	},
    {
        title: "NOW [No One Waiting]",
        artist: ["Nadia Batson", "Destra Garcia"],
        genre: ["Soca"],
        type: "ZIN 86",
        category: ["Rhythmic", "Bright", "Blast"],
		tempo: "1",
		usage: "240304",
		memo: "Zumbaのソカの曲と言えば…？できっと挙がる一曲。",
        link: "https://youtu.be/0J_g5zeUeCo?si=pwAXyk74RQ7iLvOk"
	},
    {
        title: "Chevere",
        artist: ["Marive", "feat.", "Little Big"],
        genre: ["Merengue"],
        type: "MegaMix 87",
        category: ["Bright", "Rhythmic"],
		tempo: "1",
		usage: "240102",
		memo: "Chorus（サビ）の後のパート、ラテンにはあまりないようなアクセントがありますね。",
        link: "https://youtu.be/yxqkGhVvAqY?si=zzVNUBZSSfnhTYzJ"
	},
    {
        title: "Acerela",
        artist: ["Reggi", "feat.", "Gizzle"],
        genre: ["Dubstep"],
        type: "ZIN 87",
        category: ["Cool", "Dark", "Distinctive"],
		tempo: "1",
		usage: "240901",
		memo: "とても癖が強め（そこが好き）なReggiとZIN 109のHip-Hopの楽曲でボーカルを務めているGizzleの楽曲。ギターをかき鳴らすように！",
        link: ""
	},
    {
        title: "Pa'lante",
        artist: ["Salomon Beda"],
        genre: ["Latin", "C-down"],
        type: "ZIN 87",
        category: ["Relaxing", "Emotional"],
		tempo: "1",
		usage: "240604",
		memo: "この楽曲は2020年4月、コロナ禍が始まった頃に再収録リリースされた楽曲。癒しを与える暖かな光のような歌。クールダウンによく使います。",
        link: "https://youtu.be/Y5jwkDM-AQc?si=iKhFPoqukPQ9EyI1"
	},
    {
        title: "So Sexy",
        artist: ["Max Pizzolante"],
        genre: ["Boogaloo", "Merengue"],
        type: "MegaMix 90",
        category: ["Relaxing", "Distinctive"],
		tempo: "1",
		usage: "240701",
		memo: "",
        link: "https://youtu.be/Zn0B2HcMprs?si=lgNKluS-ytk_JvkV"
	},
    {
        title: "Cinturita (Zumba Remix)",
        artist: ["Bela Hamilton"],
        genre: ["Merengue", "EDM"],
        type: "ZIN 92",
        category: ["Powerful", "Rhythmic", "Blast"],
		tempo: "1",
		usage: "240601",
		memo: "ピコピコ音のロールが特徴的な曲。頭→胸→腰→ウェーブのアイソレ要素がちょっと難しいかもです。",
        link: "https://youtu.be/cMneYC0LnEo?si=kX_ZqaXvup0xHzyQ"
	},
    {
        title: "Quisiera",
        artist: ["Willie N"],
        genre: ["Reggaeton"],
        type: "MegaMix 92",
        category: ["Relaxing"],
		tempo: "1",
		usage: "240201",
		memo: "優しい雰囲気のレゲトンソング。",
        link: "https://youtu.be/FbT5hS-sueE"
	},
    {
        title: "Bum Bum",
        artist: ["Kairo La Sinfonia"],
        genre: ["Dancehall"],
        type: "MegaMix 92",
        category: ["Dark", "Cool"],
		tempo: "1",
		usage: "240901",
		memo: "ダンスホールの振付のみで構成してます。力を溜めて開放して…抜き切らないのがポイント。",
        link: "https://youtu.be/M3deetRnsaM?si=G_url82Has4uqL91"
	},
    {
        title: "Boom Bye Bye",
        artist: ["Jota"],
        genre: ["Reggaeton", "Cumbia", "Dancehall"],
        type: "MegaMix 94",
        category: ["Dark", "Cool"],
		tempo: "1",
		usage: "240704",
		memo: "",
        link: ""
	},
    {
        title: "Go Where You Wanna Go",
        artist: ["Lolo"],
        genre: ["Latin", "C-down"],
        type: "ZIN 94",
        category: ["Powerful", "Emotional"],
		tempo: "1",
		usage: "240903",
		memo: "短めなクールダウン曲。",
        link: ""
	},
	{
        title: "Salsa De Ahora",
        artist: ["Motiff", "Los Xl del XXl"],
        genre: ["Salsa"],
        type: "MegaMix 94",
        category: ["Bright"],
		tempo: "1",
		usage: "240504",
		memo: "",
        link: "https://youtu.be/p2ewlAxN8-Y?si=Sb8a7B2GoHNI_boA"
	},
    {
        title: "Club",
        artist: ["DEMOglias", "SNDY", "Young F", "Chune"],
        genre: ["EDM"],
        type: "Megamix 95",
        category: ["Powerful", "Dark"],
		tempo: "1",
		usage: "240302",
		memo: "ジョセフZJに習いに行った振付でしています。",
        link: "https://youtu.be/Y_YJ5tIG8XM"
	},
    {
        title: "La Lista",
        artist: ["Juan Shool"],
        genre: ["Bachata"],
        type: "MegaMix 95",
        category: ["Relaxing"],
		tempo: "1",
		usage: "240501",
		memo: "こちらもジョセフZJより。後半に突然入るショルダーシミ―&ウェーブが音にピッタリ。",
        link: ""
	},
    {
        title: "Necesito",
        artist: ["Starkboys", "Dobliu"],
        genre: ["Merengue"],
        type: "MegaMix 95",
        category: ["Relaxing"],
		tempo: "1",
		usage: "240703",
		memo: "原曲とZumba Volume収録版が少し違いますね。",
        link: "https://youtu.be/r-K6u3Zzf3U?si=gz0L4U-XL9wkT2Rq"
	},
    {
        title: "Amaneci",
        artist: ["Puchu y Tucutu"],
        genre: ["Dembow", "Guaracha"],
        type: "MegaMix 96",
        category: ["Cool", "Rhythmic"],
		tempo: "1",
		usage: "240803",
		memo: "",
        link: "https://youtu.be/Ajrkot_J5Qk?si=_gWMPxcnYIe6Okmo"
	},
    {
        title: "Que Detone",
        artist: ["David DLuna"],
        genre: ["Salsa"],
        type: "MegaMix 96",
        category: ["Experimental", "Cool", "Rhythmic"],
		tempo: "1",
		usage: "240802",
		memo: "",
        link: ""
	},
    {
        title: "Papito",
        artist: ["Zumba"],
        genre: ["Cumbia", "Dembow"],
        type: "ZIN 96",
        category: ["Cool", "Experimental", "Blast"],
		tempo: "1",
		usage: "240901",
		memo: "デンボウ要素強めの速いクンビア、人気曲。ZIN 62の「Shut Up Th Dance」と似たフレーズが入ってるなぁ最近気づきました。",
        link: ""
	},
    {
        title: "Ataca",
        artist: ["Becca", "Jota"],
        genre: ["Bellydance", "Latin"],
        type: "MegaMix 97",
        category: ["Dark", "Rhythmic"],
		tempo: "1",
		usage: "240402",
		memo: "",
        link: ""
	},
    {
        title: "Que Se Repita",
        artist: ["NAP"],
        genre: ["Cumbia", "Hip-hop"],
        type: "MEgaMix 97",
        category: ["Experimental"],
		tempo: "1",
		usage: "240402",
		memo: "",
        link: "https://youtu.be/7cDmucuDGHQ?si=zotRwLt8EQUXnG4j"
	},
    {
        title: "Tu Cara Bonita",
        artist: ["Zumba"],
        genre: ["Bachata"],
        type: "MegaMix 97",
        category: ["Emotional"],
		tempo: "1",
		usage: "240601",
		memo: "",
        link: ""
	},
    {
        title: "La Batidora (Zumba Remix)",
        artist: ["Sofia Reyes", "El Gran Silencio"],
        genre: ["Cumbia"],
        type: "MegaMix 98",
        category: ["Emotional", "Experimental"],
		tempo: "1",
		usage: "240304",
		memo: "歌詞の中にサルサの女王セリア・クルーズの歌から引用があります。「このサウンドリズムにのって踊り続けよう、悲しみを手放すんだ」どんなシーンの曲なんでしょうね。",
        link: "https://youtu.be/eeN7tHYQorE?si=-JdIsr7Nu4fl3em2"
	},
    {
        title: "Tempo",
        artist: ["Jenn Morel"],
        genre: ["Dembow"],
        type: "ZIN 98",
        category: ["Dark"],
		tempo: "1",
		usage: "240402",
		memo: "",
        link: "https://youtu.be/ToSDqW69mXk?si=SQ7iyAIT75OHDxyv"
	},
    {
        title: "Baloncito Viejo",
        artist: ["Carlos Vives", "Camilo"],
        genre: ["Vallenato"],
        type: "ZIN 98",
        category: ["Relaxing", "Emotional"],
		tempo: "1",
		usage: "240603",
		memo: "バジェナートといえば！のCarlos Vives。優しい雰囲気の楽曲ですね。",
        link: "https://youtu.be/fOAYjG_G4xY?si=-IDiwwJk1KwDiR4C"
	},
	{
        title: "Mi Forma De Ser (Salsa Version)",
        artist: ["Olga Tañon"],
        genre: ["Salsa"],
        type: "ZIN 99",
        category: ["Bright", "Relaxing", "Emotional"],
		tempo: "1",
		usage: "240604",
		memo: "サルサバージョンのみZumba Volumeに収録。メレンゲ版と同じような振付になるようにしています。",
        link: "https://youtu.be/mdFpJO9H_U8"
    },
    {
        title: "Overtime",
        artist: ["Dahrio", "Joellii", "Jhon Hart", "Mario Parra"],
        genre: ["Funk"],
        type: "MegaMix 99",
        category: ["Blast", "Rhythmic"],
		tempo: "1",
		usage: "240701",
		memo: "4つ打ちのリズムだけでなく&カウントのビートにのってもらえるような振付にしました。指差しで4方向回転は時計をイメージ。BttFの時計塔みたく時を戻してます。",
        link: ""
	},
    {
        title: "Reset",
        artist: ["Joey Montana"],
        genre: ["Soca", "Pop"],
        type: "ZIN 99",
        category: ["Relaxing"],
		tempo: "1",
		usage: "240103",
		memo: "",
        link: ""
	},
    {
        title: "Asi Eh, Just Like That!",
        artist: ["Oro Solido"],
        genre: ["Merengue"],
        type: "ZIN 99",
        category: ["Bright", "Rhythmic", "Distinctive"],
		tempo: "1",
		usage: "240601",
		memo: "Oro Solido(Raul Acosta)の曲の中でもイントロ、コーラス等の分かれ目が分かりやすい曲、大すき。点心を落とさないように「おっとっと！」",
        link: ""
	},
    {
        title: "Yo Te Conozco",
        artist: ["Max Pizzolante"],
        genre: ["Merengue"],
        type: "ZIN 99",
        category: ["Cool", "Rhythmic"],
		tempo: "1",
		usage: "240503",
		memo: "",
        link: ""
	},
    {
        title: "Tu Tiene' El Flow",
        artist: ["Zumba"],
        genre: ["EDM", "Pop"],
        type: "ZIN 99",
        category: ["Bright", "Relaxing"],
		tempo: "1",
		usage: "240501",
		memo: "",
        link: ""
	},
    {
        title: "Tus Pies",
        artist: ["Pinto Picasso"],
        genre: ["Flamenco", "Urban"],
        type: "MegaMix 99",
        category: ["Cool", "Blast"],
		tempo: "1",
		usage: "240803",
		memo: "この曲からフラメンコに目覚めました！",
        link: ""
	},
    {
        title: "Fuego Lento",
        artist: ["Zumba"],
        genre: ["Salsa"],
        type: "MegaMix 99",
        category: ["Bright", "Distinctive"],
		tempo: "1",
		usage: "240603",
		memo: "空耳シリーズ「えぇ～やん！」表情も大切に！笑",
        link: ""
	},
    {
        title: "Pa Bailar",
        artist: ["Juan Magan", "Topo La Maskara", "Mr.Vegas"],
        genre: ["Dancehall"],
        type: "ZIN 100",
        category: ["Dark", "Cool"],
		tempo: "1",
		usage: "240401",
		memo: "レゲトンのような弾けるキックがありません。「重さ」を見て感じられる、波のような動きが目指せるといいですね。",
        link: "https://music.youtube.com/watch?v=PGQJGkbD8KM&si=Cnu9bduolZWQjPa5&feature=xapp_share"
	},
    {
        title: "Berlin",
        artist: ["Zion", "Lennox", "Maria Becerra"],
        genre: ["Latin", "House"],
        type: "ZIN 100",
        category: ["Dark", "Cool", "Emotional", "Blast"],
		tempo: "1",
		usage: "「忘れられない人を探して。LA, New York, Berlinと世界中を探している」そんな曲です。遠くを指さして「あっちこっち」",
		memo: "241004",
        link: "https://youtu.be/5Eed1XaWgDI?si=1XsGjkRER2IMRVpX"
	},
    {
        title: "Me Albrota",
        artist: ["Zumba"],
        genre: ["Salsa"],
        type: "MegaMix 100",
        category: ["Relaxing"],
		tempo: "1",
		usage: "240802",
		memo: "",
        link: ""
	},
    {
        title: "Chilling",
        artist: ["The Flow", "BIP"],
        genre: ["Soca"],
        type: "MegaMix 100",
        category: ["Powerful", "Dark", "Blast"],
		tempo: "1",
		usage: "240802",
		memo: "激しく動くパートの後はバイクをイメージ。レッグカールしながら「ブゥォン！」とエンジンをふかすように。",
        link: "https://youtu.be/9_QglowL9Hc?si=62gYn5-czN3Wx0Pn"
	},
    {
        title: "Sah Sah (Zumba Remix)",
        artist: ["Nancy Ajram", "Marshmello"],
        genre: ["Bellydance", "Guaracha"],
        type: "ZIN 101",
        category: ["Experimental", "Rhythmic", "Dark"],
		tempo: "1",
		usage: "240304",
		memo: "Zumbaスタジオによるワラチャアレンジが格好いい曲。",
        link: "https://youtu.be/eUfU31LrTqQ?si=wcmHtqxIAXAIeT9V"
	},
    {
        title: "Tengo Un Amor",
        artist: ["Los Enbajadres de la Salsa"],
        genre: ["Salsa", "Cumbia"],
        type: "ZIN 101",
        category: ["Bright", "Blast", "Rhythmic"],
		tempo: "1",
		usage: "240301",
		memo: "歌詞の全てから愛する人への想いが溢れまくってる曲。振付もそれに合わせて作りました。名前が変わったりもしていますがアーティスト「Los Enbajadres de la Salsa」格好いい曲ばかりなので聞いてみてください。",
        link: "https://youtu.be/FCYkWbPmRfo"
	},
    {
        title: "Ella Quiere Mambo (Zumba Version)",
        artist: ["E Tune"],
        genre: ["Merengue"],
        type: "ZIN 101",
        category: ["Power", "Rhythmic"],
		tempo: "1",
		usage: "240601",
		memo: "短めなメレンゲ曲。",
        link: "https://youtu.be/tzZC26HDgqI"
	},
    {
        title: "Con Ganas",
        artist: ["Zumba"],
        genre: ["Bachata", "Fusion"],
        type: "ZIN 101",
        category: ["Bright", "Rhythmic", "Distinctive"],
		tempo: "1",
		usage: "241004",
		memo: "手を合わせてスリスリ、多くのインストラクターが取り入れてますね。",
        link: ""
	},
    {
        title: "Mareao",
        artist: ["OKAA"],
        genre: ["Soca"],
        type: "MegaMix 101",
        category: ["Bright", "Power", "Rhythmic"],
		tempo: "1",
		usage: "240803",
		memo: "",
        link: ""
	},
    {
        title: "Eres Tu",
        artist: ["Mara Prada", "Robert Taylor"],
        genre: ["Reggaeton"],
        type: "MegaMix 101",
        category: ["Experimental"],
		tempo: "1",
		usage: "241004",
		memo: "最近の曲調ではないような音の使い方をするレゲトン曲。基本の動きに忠実に、ちょっと遊びも入れながら。",
        link: ""
	},
    {
        title: "Ay Dios",
        artist: ["CNCO"],
        genre: ["Reggaeton", "Cumbia"],
        type: "ZIN 102",
        category: ["Emotional", "Relaxing"],
		tempo: "1",
		usage: "240402",
		memo: "CNCOはオシャレなレゲトン曲が多いですね。",
        link: "https://youtu.be/r5o8Dyn8aiQ"
	},
    {
        title: "Let It Out",
        artist: ["Active Nation"],
        genre: ["Bachata", "EDM"],
        type: "ZIN 102",
        category: ["Dark", "Powerful", "Experimental"],
		tempo: "1",
		usage: "240502",
		memo: "前半はバチャータのリズム、後半はビートの強いダンス系。",
        link: ""
	},
    {
        title: "Monotonia",
        artist: ["Shakira", "Ozuna"],
        genre: ["Bachata"],
        type: "ZIN 102",
        category: ["Emotional", "Relaxing"],
		tempo: "1",
		usage: "240503",
		memo: "",
        link: "https://youtu.be/j5y6xLpRwx4?si=b35MAgJi0lq5lCYG"
	},
    {
        title: "Besame",
        artist: ["Moino"],
        genre: ["Flamenco"],
        type: "MegaMix 102",
        category: ["Experimental", "Rhythmic"],
		tempo: "1",
		usage: "240904",
		memo: "シンセサイザーの音が入ったフラメンコ。",
        link: ""
	},
    {
        title: "Sha La La",
        artist: ["David DLuna"],
        genre: ["Afrobeat"],
        type: "MegaMix 102",
        category: ["Relaxing", "Emotional", "Distinctive"],
		tempo: "1",
		usage: "241004",
		memo: "雨の音から入る静かな曲。振り一つひとつが楽器の音に合うようにしているので聞いてみてください。",
        link: ""
	},
    {
        title: "Timba",
        artist: ["Zumba"],
        genre: ["Cumbia"],
        type: "ZIN 103",
        category: ["Dark", "Traditional"],
		tempo: "1",
		usage: "240403",
		memo: "",
        link: ""
	},
	{
        title: "Azucar",
        artist: ["BIP"],
        genre: ["Salsa", "Trap"],
        type: "ZIN 103",
        category: ["Cool", "Experimental", "Blast"],
		tempo: "1",
		usage: "240602",
		memo: "",
        link: ""
	},
    {
        title: "Revolu",
        artist: ["ZZ"],
        genre: ["Reggaeton"],
        type: "MegaMix 103",
        category: ["Rhythmic", "Emotional", "Distinctive"],
		tempo: "1",
		usage: "241003",
		memo: "公開されて1日で振付作りました笑。ぜんまい仕掛けの踊る人形みたいなイメージで振付しました。",
        link: ""
	},
    {
        title: "Baila Pa' Mi",
        artist: ["Haniset"],
        genre: ["Salsa", "Afrobeat"],
        type: "ZIN 104",
        category: ["Experimental", "Rhythmic"],
		tempo: "1",
		usage: "240201",
		memo: "前半のアフロビートは出来るだけ滑らかに、後半のサルサは力強く。対比がはっきりするといいですよね。",
        link: ""
	},
    {
        title: "Sapeca",
        artist: ["Aroxa", "feat.", "Topo La Maaskara", "3 Tenores"],
        genre: ["Brazilian Funk"],
        type: "ZIN 104",
        category: ["Traditional", "Rhythmic"],
		tempo: "1",
		usage: "240201",
		memo: "",
        link: "https://youtu.be/6EcsIy_FUfg?si=gAJY1U_4gagdg0It"
	},
    {
        title: "Arranca",
        artist: ["Becky G", "feat.", "Omega"],
        genre: ["Mambo", "Merengue"],
        type: "ZIN 104",
        category: ["Experimental", "Rhythmic"],
		tempo: "1",
		usage: "240802",
		memo: "",
        link: "https://youtu.be/sCEV3YzPCnw"
	},
    {
        title: "Beautiful",
        artist: ["Mara Prada", "Robert Taylor"],
        genre: ["Mambo", "Fusion"],
        type: "ZIN 105",
        category: ["Bright", "Rhythmic", "Blast"],
		tempo: "1",
		usage: "240801",
		memo: "Mara Prada x Robert TaylorのMambo。ほぼCrazy Loveやん（最高！）と思ってました。Warm-upに取り入れてることが多いです。",
        link: "https://youtu.be/qg41mcLpE1w?si=2kbcdhWBicp6fKFG"
	},
    {
        title: "Como E'",
        artist: ["Zumba"],
        genre: ["Salsa Choke"],
        type: "ZIN 105",
        category: ["Bright", "Rhythmic"],
		tempo: "1",
		usage: "240502",
		memo: "",
        link: ""
	},
    {
        title: "Vagabundo",
        artist: ["Sebastián Yatra", "Manuel Turizo", "Beéle"],
        genre: ["Pop", "Merengue"],
        type: "ZIN 105",
        category: ["Relaxing", "Distinctive", "Emotional"],
		tempo: "1",
		usage: "240502",
		memo: "これも振付が特徴的ですね。",
        link: "https://youtu.be/0J1hIERZ1yA?si=wESv-626-NVH3v6a"
	},
    {
        title: "A Contra Tiempo",
        artist: ["Santander"],
        genre: ["Bachata", "Reggae", "Merengue"],
        type: "ZIN 106",
        category: ["Emotional", "Rhythmic"],
		tempo: "1",
		usage: "240601",
		memo: "",
        link: ""
	},
    {
        title: "Com Pila De Sed",
        artist: ["Chimbara"],
        genre: ["Afrobeat", "Dembow"],
        type: "ZIN 106",
        category: ["Distinctive", "Experimental", "Rhythmic"],
		tempo: "1",
		usage: "240502",
		memo: "デンボウ要素強め、振付はオリジナルで印章強めに。因みにアーティストのChimbaraは「モケケパケケ」部分じゃなくてこぶしのある声の男性。",
        link: ""
	},
    {
        title: "Funk Rave",
        artist: ["Anitta"],
        genre: ["Brazilian Funk"],
        type: "ZIN 106",
        category: ["Cool", "Rhythmic", "Dark"],
		tempo: "1",
		usage: "240302",
		memo: "強いビートと「ずっっちゃっちゃずっちゃっちゃ」",
        link: "https://youtu.be/srmxQt0QNR4?si=9-ujaXf2FgR6-oxI"
	},
    {
        title: "Mucho Flow",
        artist: ["Ilgales", "Happy Colors"],
        genre: ["Latin", "Pop"],
        type: "ZIN 106",
        category: ["Bright", "Rhythmic", "Blast"],
		tempo: "1",
		usage: "240303",
		memo: "たまにある「たくさんのインストラクターが使ってて、誰でもきっと好きになる曲。」",
        link: "https://youtu.be/VolmYSTcUzM?si=K8qDlBJFtu13gTDB"
	},
    {
        title: "Cumbia Bacana",
        artist: ["Zumba"],
        genre: ["Cumbia"],
        type: "ZIN 106",
        category: ["Powerful", "Traditional"],
		tempo: "1",
		usage: "240701",
		memo: "ZIN 67 のEsta Nocheのフレーズが入ってますね。メロディよりも裏のビートや掛け声などに合わせた振り付けにしています。",
        link: ""
	},
    {
        title: "Chillin",
        artist: ["HIZO_888", "Topo La Maskara", "DavidDLuna"],
        genre: ["Brazilian Funk", "Latin"],
        type: "ZIN 106",
        category: ["Emotional", "Rhythmic"],
		tempo: "1",
		usage: "240601",
		memo: "",
        link: "https://youtu.be/dhDhjmsz4aI?si=mIX3-9dfybIau97y"
	},
    {
        title: "Metele Saoco",
        artist: ["Pinto Picasso"],
        genre: ["Merengue", "Reggaeton"],
        type: "ZIZN 106",
        category: ["Dark", "Powerful"],
		tempo: "1",
		usage: "240402",
		memo: "",
        link: ""
	},
    {
        title: "Dientes",
        artist: ["J Balvin", "Usher", "DJ Khaled"],
        genre: ["Urban", "Pop"],
        type: "ZIN 107",
        category: ["Powerful", "Distinctive"],
		tempo: "1",
		usage: "240301",
		memo: "バルヴィン、アッシャーとメジャーなアーティストによるアーバンポップ。",
        link: "https://youtu.be/gVPgwoXm5Rc?si=yLk80z5z3UXXJWiU"
	},
    {
        title: "Mueve El Cuerpo",
        artist: ["Ronald Borjas"],
        genre: ["Salsa"],
        type: "ZIN 107",
        category: ["Rhythmic", "Traditional"],
		tempo: "1",
		usage: "240304",
		memo: "",
        link: ""
	},
    {
        title: "Me Buscas",
        artist: ["Pinto Picasso"],
        genre: ["Brazilan Funk", "Fusion"],
        type: "ZIN 107",
        category: ["Powerful", "Cool"],
		tempo: "1",
		usage: "240602",
		memo: "",
        link: ""
	},
    {
        title: "Mas Que to Amigo",
        artist: ["Hey Broders"],
        genre: ["Cumbia"],
        type: "ZIN 108",
        category: ["Emotional", "Relaxing"],
		tempo: "1",
		usage: "240801",
		memo: "",
        link: "https://youtu.be/VEp_2nGB0AU?si=fHLUhG-q2xjQeNw-"
	},
    {
        title: "Batea",
        artist: ["Magic Juan", "feat.", "Kiko El Crazy"],
        genre: ["Merengue"],
        type: "ZIN 108",
        category: ["Powerful", "Distinctive"],
		tempo: "1",
		usage: "240502",
		memo: "野球の振付をしているインストラクターが多かったですね。",
        link: "https://youtu.be/bbNl15ffEv8?si=5sxThIvwtrh4MoFW"
	},
    {
        title: "On That Feeling",
        artist: ["Nalya K"],
        genre: ["Brazilian Funk"],
        type: "ZIN 108",
        category: ["Experimental"],
		tempo: "1",
		usage: "240401",
		memo: "",
        link: ""
	},
    {
        title: "Ya No Extrano",
        artist: ["Natti Natasha"],
        genre: ["Reggaeton"],
        type: "ZIN 109",
        category: ["Bright", "Relaxing", "Distinctive"],
		tempo: "1",
		usage: "240503",
		memo: "ダークな雰囲気の曲を得意とするナターシャの明るい曲。Youtubeで探したらクンビアバージョンもあります。",
        link: "https://youtu.be/EWmyO1yWKls?si=S7Iovd5NgZQKu1K1"
	},
    {
        title: "Te Provoca",
        artist: ["Lion Lazaro"],
        genre: ["Salsa"],
        type: "ZIN 109",
        category: ["Experimental", "Rhythmic"],
		tempo: "1",
		usage: "240601",
		memo: "",
        link: ""
	},
    {
        title: "M.I.A.M.I.",
        artist: ["Nacho"],
        genre: ["Cubaton", "Afrobeat"],
        type: "ZIN 109",
        category: ["Dark", "Rhythmic"],
		tempo: "1",
		usage: "240802",
		memo: "",
        link: "https://example.com"
    },
    {
        title: "Sueltate El Pelo",
        artist: ["Pinto Picasso"],
        genre: ["Merengue", "Fusion"],
        type: "ZIN 109",
        category: ["Cool", "Rhythmic"],
		tempo: "1",
		usage: "240502",
		memo: "",
        link: ""
	},
    {
        title: "Aprieta",
        artist: ["Max Pizzolante"],
        genre: ["Salsa", "Afrobeat"],
        type: "ZIN 110",
        category: ["Rhythmic", "Distinctive"],
		tempo: "1",
		usage: "240703",
		memo: "",
        link: "https://youtu.be/RcbwlEejylI?si=oJ3w6M79XNXb0D52"
	},
    {
        title: "Barcelona",
        artist: ["Leslie Shawn"],
        genre: ["Merengue"],
        type: "ZIN 110",
        category: ["Rhythmic", "Experimental"],
		tempo: "1",
		usage: "240601",
		memo: "",
        link: ""
	},
    {
        title: "La Dieta",
        artist: ["Guaynaa"],
        genre: ["Cumbia", "Urban"],
        type: "ZIN 110",
        category: ["Powerful", "Traditional"],
		tempo: "1",
		usage: "240602",
		memo: "",
        link: "https://youtu.be/S61iMZDiN_w?si=XKozmGriyFHjBIYY"
	},
    {
        title: "Lo Nuestro",
        artist: ["Bela"],
        genre: ["Bachata"],
        type: "ZIN 110",
        category: ["Distinctive", "Relaxing", "Emotional"],
		tempo: "1",
		usage: "240603",
		memo: "",
        link: ""
	},
    {
        title: "Muevence",
        artist: ["Mark Anthony"],
        genre: ["Salsa"],
        type: "ZIN 111",
        category: ["Distinctive", "Experimental", "Rhythmic"],
		tempo: "1",
		usage: "240703",
		memo: "少し難解な進行をするサルサ曲。「よくわからんけど格好いい」と思ってます。",
        link: "https://youtu.be/gruomptSqq0?si=rM4co35G7SdzWog1"
	},
    {
        title: "Mujeron",
        artist: ["Mannel"],
        genre: ["Cumbia"],
        type: "ZIN 111",
        category: ["Bright", "Distinctive"],
		tempo: "1",
		usage: "240901",
		memo: "「指さし→口元」の振付はきっとみんな大好き！",
        link: ""
	},
    {
        title: "Una Fiesta",
        artist: ["Reggi El Autentico"],
        genre: ["Bachata", "Fusion", "Afrobeat"],
        type: "ZIN 111",
        category: ["Relaxing"],
		tempo: "1",
		usage: "240703",
		memo: "",
        link: ""
	},
    {
        title: "Let's Freak",
        artist: ["Robbie Elias" ,"BIP"],
        genre: ["Disco", "Dembow"],
        type: "ZIN 111",
        category: ["Cool", "Powerful", "Rhythmic"],
		tempo: "1",
		usage: "240804",
		memo: "ディスコ！知らないけど雰囲気をイメージしてオリジナル振付しました。後半のDembowパートは力強くかつ滑らかに。",
        link: "https://youtu.be/LPcUQBMKW-o?si=52PoVX7i4TKfh8Va"
	},
    {
        title: "Sushi Azul",
        artist: ["Max Pizzolante"],
        genre: ["Merengue"],
        type: "ZIN 111",
        category: ["Cool", "Powerful", "Rhythmic"],
		tempo: "1",
		usage: "240803",
		memo: "曲名のSushiはジャケット見る限り寿司っぽいですね。",
        link: "https://youtu.be/LPcUQBMKW-o?si=52PoVX7i4TKfh8Va"
	},
    {
        title: "Si Antes Te Hubiera Conocido",
        artist: ["Karol G"],
        genre: ["Merengue"],
        type: "ZIN 112",
        category: ["Emotional"],
		tempo: "1",
		usage: "240903",
		memo: "「もっとはやくあなたに出会えてたら」優しい、でも少しもの悲しい曲。ZESのLorettaとNickの振付がベースです。",
        link: "https://youtu.be/MgsdDfdGdHc?si=p3JLLxX7l8ed0H6Q"
    },
    {
        title: "La Cumbia",
        artist: ["Zumba"],
        genre: ["Cumbia"],
        type: "ZIN 112",
        category: ["Distinctive", "Traditional"],
		tempo: "1",
		usage: "240901",
		memo: "基本オリジナル振付ですね。音の強弱を体で表現してもらいたくて「静かに！」の指示が多いです。皆様の予想の3倍は出してます笑",
        link: ""
	},
    {
        title: "Mi Cora",
        artist: ["DK"],
        genre: ["Caribbean", "Fusion"],
        type: "ZIN 112",
        category: ["Bright", "Rhythmic"],
		tempo: "1",
		usage: "240902",
		memo: "",
        link: ""
	},
    {
        title: "Rapapari",
        artist: ["Magic Juan", "feat.", "El Pekeño"],
        genre: ["Merengue"],
        type: "ZIN 113",
        category: ["Bright", "Blast", "Distinctive"],
		tempo: "1",
		usage: "241004",
		memo: "ZES JeffとZJ MIZUKIの振付で踊っています。Zumbaに慣れてきたら楽しく踊れること間違いなし！エレキベース・ギターがとても気持ちいい一曲。",
        link: ""
	},
    {
        title: "Insomnio",
        artist: ["Nicky Jam"],
        genre: ["Bachata", "Fusion"],
        type: "ZIN 113",
        category: ["Emotional", "Cool"],
		tempo: "1",
		usage: "241003",
		memo: "イントロでハートを掴まれてしまった曲。こちらもおふたりの振付。メロディや楽器、曲の雰囲気に合う振付で大好きです。",
        link: ""
	},
    {
        title: "Help Me!",
        artist: ["The Moonsters", "Enric Font", "feat.", "Lexter"],
        genre: ["EDM"],
        type: "KIDS 2017 JUL",
        category: ["Cool", "Powerful", "Blast"],
		tempo: "1",
		usage: "240301",
		memo: "夜が想起されるダンスミュージック。この楽曲はWarm-upに用いることが多いですね。",
        link: "https://youtu.be/tCeW-DFbcgw"
	},
    {
        title: "Punta Tacon",
        artist: ["Eduardo Imbelloni"],
        genre: ["Flamenco"],
        type: "KIDS 2018 APR",
        category: ["Rhythmic"],
		tempo: "1",
		usage: "240801",
		memo: "短めなフラメンコ曲。「ぷんぷん！」と怒る仕草の振りも考えましたが、あざとさが思ったより酷く自ら却下しました笑",
        link: ""
	},
    {
        title: "Arabian Flow",
        artist: ["Zumba"],
        genre: ["Arabic", "Salsa", "Bellydance"],
        type: "KIDS 2018 NOV",
        category: ["Traditional", "Distinctive"],
		tempo: "1",
		usage: "241004",
		memo: "元々ジャンルはアラビック・サルサ。キックやパーカッションの音に合わせたベリーダンスの振付にしています。雰囲気や顔の向きを大切に。",
        link: ""
	},
    {
        title: "Soy Yo",
        artist: ["Bomba Esteleo"],
        genre: ["Cumbia"],
        type: "KIDS 2019 SEP",
        category: ["Bright", "Experimental"],
		tempo: "1",
		usage: "240602",
		memo: "「何言われても、私は私。これが私よ！」という歌。アニメーション映画「Sing 2」の劇中歌にも使われてます。",
        link: "https://youtu.be/bxWxXncl53U"
	},
    {
        title: "Hulk",
        artist: ["Blaxx"],
        genre: ["Soca"],
        type: "KIDS 2021 AUG",
        category: ["Powerful", "Distinctive", "Blast"],
		tempo: "1",
		usage: "240904",
		memo: "マーベルヒーローのハルクですね。ハルクとブルース博士の様に力強く荒々しいところ、またそれ以外をきっちり分けて動けるといいですね。",
        link: "https://youtu.be/WRT3lBem0Ck?si=M8BVfrK3-bBDUnQu"
	},
    {
        title: "Born Ready",
        artist: ["Aaron Duncan"],
        genre: ["Soca"],
        type: "KIDS 2021 NOV",
        category: ["Powerful", "Rhythmic"],
		tempo: "1",
		usage: "240201",
		memo: "",
        link: "https://youtu.be/BdokhLg2LaE"
	},
    {
        title: "Her",
        artist: ["Topo La Maskara", "Berra"],
        genre: ["Afrobeat"],
        type: "KIDS 2023 MAR",
        category: ["Relaxing"],
		tempo: "1",
		usage: "240302",
		memo: "",
        link: ""
	},
    {
        title: "Sube La Mano",
        artist: ["Zumba"],
        genre: ["Merengue"],
        type: "KIDS 2024 JUL",
        category: ["Bright", "Rhythmic", "Distinctive"],
		tempo: "1",
		usage: "240902",
		memo: "コーラスでは曲名の「手を挙げてね！」を意識した振付。泳ぐ振付を入れてるのはこの曲だけかも？",
        link: ""
	},
    {
        title: "Cyberpunk",
        artist: ["ATEEZ"],
        genre: ["K-Pop", "Pop"],
        type: "Others",
        category: ["Powerful", "Cool", "Dark"],
		tempo: "1",
		usage: "240404",
		memo: "強いビートのK-Pop。どんどん変わる声色に合わせた振付にしました。",
        link: "https://youtu.be/nHFd4eEBvP4?si=RGUeuXGRd8Hp1i4i"
	},
    {
        title: "It's Plenty",
        artist: ["Burna Boy"],
        genre: ["Afrobeat", "Fusion"],
        type: "Others",
        category: ["Emotional", "Relaxing"],
		tempo: "1",
		usage: "240603",
		memo: "",
        link: "https://youtu.be/F8bZVnynDdc?si=GWnevmOKOkiSvoGc"
	},
    {
        title: "Ram Pam Pam",
        artist: ["Natti Natasha", "feat.", "Becky G"],
        genre: ["Reggaeton", "Cumbia", "Urban"],
        type: "Others",
        category: ["Dark", "Rhythmic"],
		tempo: "1",
		usage: "240402",
		memo: "",
        link: "https://youtu.be/_wE3hDN06Qg?si=9lDtR1mi3l2L-mkp"
	},
    {
        title: "Santorini",
        artist: ["Beéle", "Farruko"],
        genre: ["Latin"],
        type: "Others",
        category: ["Emotional"],
		tempo: "1",
		usage: "240301",
		memo: "高音の透き通る声のBeéle（ZIN 108 のBachataもこの方）とEmotionalなレゲトンを歌い上げるFarrukoのコラボ曲。",
        link: "https://youtu.be/FS__SaIBf-A?si=BwYeaXnwgqtOk-KS"
	},
    {
        title: "Thriller (Steve Aoki Midnight Hour Remix)",
        artist: ["Michael Jackson"],
        genre: ["EDM", "Rock"],
        type: "Others",
        category: ["Powerful", "Dark", "Cool", "Blast"],
		tempo: "1",
		usage: "241003",
		memo: "著名なDJスティーブ・アオキによるリミックス曲。オリジナルMVの有名な振付も取り入れてます。",
        link: "https://youtu.be/b0RyiTp8gSA?si=e0guIh63oFiu_DpS"
	},
    {
        title: "Yo No Fui",
        artist: ["Croocked Stilo", "El Dusty"],
        genre: ["Cumbia"],
        type: "Others",
        category: ["Dark", "Traditional"],
		tempo: "1",
		usage: "241003",
		memo: "ハロウィーンの季節にピッタリのクンビア。ジャケットは死者の日を想起させますね。",
        link: "https://youtu.be/rn9tEErGMik?si=mixHpnvaCO2MLFdZ"
	},
    {
        title: "Volare",
        artist: ["Gipsy Kings"],
        genre: ["Flamenco"],
        type: "Others",
        category: ["Bright", "Powerful", "Traditional", "Blast"],
		tempo: "1",
		usage: "240701",
		memo: "CMで聞いたことがある人も多いはず。力強い声と演奏に乗せて踊りましょう！",
        link: "https://youtu.be/X8TOhb_4jU0?si=tQC6KAf9kbTfqtcC"
	},
    {
        title: "Mi Forma De Ser",
        artist: ["Olga Tañon"],
        genre: ["Merengue"],
        type: "Others",
        category: ["Bright", "Emotional", "Rhythmic"],
		tempo: "1",
		usage: "241002",
		memo: "元は他アーティストの楽曲。メレンゲにアレンジされて力強く歌い上げているのが格好いいです。",
        link: "https://youtu.be/w9_1RuFkqzA?si=7wsXy_5001KQMepd"
	},
    {
        title: "Tu Amor, More, More",
        artist: ["Chino", "Nacho"],
        genre: ["Latin"],
        type: "Others",
        category: ["Bright", "Rhythmic"],
		tempo: "1",
		usage: "240603",
		memo: "M.I.A.M.I.などの曲も手掛けているNachoがソロで活動する前にリリースした曲のひとつ。音にはまる気持ちいい！そんな振付を目指しました。",
        link: "https://youtu.be/dR8dBCzs2EY?si=oW86LMbQax-TlXb7"
	},
    {
        title: "Soñer(Breaker)",
        artist: ["NMIXX"],
        genre: ["K-Pop", "Pop"],
        type: "Others",
        category: ["Cool", "Experimental", "Distinctive"],
		tempo: "1",
		usage: "240904",
		memo: "振付は韓国のZES Jennifer Kimに習いました。ガールズK-Popらしいところ力強いところと1曲に色んな面がみられます。",
        link: "https://youtu.be/4_vzrcxpT4I?si=afr5f_HCG2jDPcF9"
	},
    {
        title: "Bling-Bang-Bang-Born [Merengue]",
        artist: ["Creepy Nuts", "The Covers Duo"],
        genre: ["Hip-hop", "Merengue"],
        type: "Others",
        category: ["Distinctive", "Powerful", "Blast"],
		tempo: "1",
		usage: "240504",
		memo: "世界で流行したCreepy Nutsの楽曲のメレンゲカバー版。",
        link: "https://youtu.be/pYOgZFtjcas?si=4irg6zsQtApILFm3"
	},
    {
        title: "Perhaps, Perhaps, Perhaps",
        artist: ["Daniel Boaventura"],
        genre: ["Cha-cha-cha"],
        type: "Others",
        category: ["Relaxing", "Cool"],
		tempo: "1",
		usage: "240801",
		memo: "",
        link: "https://youtu.be/EgknmfB7Ux4?si=x-G1Llbv-SIMs13c"
	},
    {
        title: "Bambilambambilambilambam",
        artist: ["Farmer Nappy"],
        genre: ["Soca"],
        type: "Others",
        category: ["Bright", "Experimental"],
		tempo: "1",
		usage: "240901",
		memo: "曲名間違っていません笑。カーニバル！盛り上がろうぜっ！そんな一曲。",
        link: "https://youtu.be/XXEVLxTUAsM?si=1O2BllwaF1tGaJXA"
	},
    {
        title: "Dreamers",
        artist: ["JUNG KOOK", "BTS"],
        genre: ["Pop"],
        type: "Others",
        category: ["Emotional"],
		tempo: "1",
		usage: "241004",
		memo: "「さぁ見て僕らを、僕らは夢を追う者たち」挑戦し戦い続ける人へ向けたエールの曲。振付はアフロビートを中心に構成。",
        link: "https://youtu.be/Jm29kLeWqDA?si=nXPXVMMtoMvAC3cQ"
	},
    {
        title: "Galway Girl",
        artist: ["Ed Sheeran"],
        genre: ["Pop", "Folk"],
        type: "Others",
        category: ["Pop", "Emotional", "Traditional"],
		tempo: "1",
		usage: "241004",
		memo: "イギリスのアーティストエドシーランの一曲。特徴的なバイオリンの奏法などフォークミュージックの一面もある格好いい曲です。",
        link: "https://youtu.be/87gWaABqGYs?si=1ghDXpzw5rjUbClA"
	},
    {
        title: "To My Love (Tainy Remix)",
        artist: ["Bomba Esteleo"],
        genre: ["Pop", "Reggaeton", "Latin"],
        type: "Others",
        category: ["Relaxing", "Distinctive"],
		tempo: "1",
		usage: "240904",
		memo: "",
        link: "https://youtu.be/THBP1tq49wk?si=r6WQFqTjd7e4BIoY"
	},
    {
        title: "Fuego",
        artist: ["Dimitri Vegas", "Like Mike", "Kim Loaiza"],
        genre: ["Reggaeton", "Dancehall", "Latin"],
        type: "Others",
        category: ["Dark", "Distinctive", "Emotional"],
		tempo: "1",
		usage: "241003",
		memo: "",
        link: "https://youtu.be/rMCnyJgEjnA?si=IBDYYPGwn308WcXe"
	}



];


